site:
  title: "Luiz Fernando Maehana | Currículo Web"
  description: "Sou o Luiz Fernando Maehana, formado em Sistemas para Internet (Web Design) pela UniCesumar, tenho certificação Microsoft em desenvolvimento com HTML5, CSS3 e JavaScript, fiz diversos cursos na área de Front-End e Back-End, além de ter ido em vários eventos de tecnologia, busco sempre compartilhar meu conhecimento e continuar aprendendo."
personal:
  name: "Luiz Fernando Maehana"
  job: "Desenvolvedor Full Stack"
  initial: "LM"
  avatar: "https://github.com/luiz-maehana.png"
  logo: "https://maehana.com.br/assets/images/logo.png"
  socialNetworks:
    linkedin: "https://www.linkedin.com/in/luizmaehana"
    github: "https://github.com/luiz-maehana"
    instagram: "https://www.instagram.com/luiz.maehana"
